Repository unb-mds/2024-1-EducaMinas-frontend, pull requests merged in 2024-05, with the labels that each got.

#55 Feature #54/ranking component
  src/app/search/page.tsx
  src/components/Ranking.tsx
  tailwind.config.ts
Labels: feature

#57 docs(#56): Updates sprint 4 documentation and includes sprint 5
  docs/docs/index.md
  docs/docs/sprints/sprint-4.md
  docs/docs/sprints/sprint-5.md
  docs/mkdocs.yml
Labels: documentation

#59 Feature #58/second topic search page
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/Filter.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.tsx
  src/components/Topics.tsx
  src/components/chart/GroupedBar.tsx
  tailwind.config.ts
Labels: feature, design
