Repository unb-mds/2024-1-EducaMinas-frontend, pull requests merged in 2024-07, with the labels that each got.

#60 Documentation and other features
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/docs/index.md
  docs/docs/project/arquitetura.md
  docs/docs/sprints/sprint-4.md
  docs/docs/sprints/sprint-5.md
  docs/mkdocs.yml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/ChartBar.tsx
  src/components/Filter.tsx
  src/components/Header.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.tsx
  src/components/Topics.tsx
  src/components/chart/GroupedBar.tsx
  src/components/chart/StackedColumn.tsx
  tailwind.config.ts
Labels: documentation

#64 Feature #62/update sprints documentation
  docs/docs/sprints/sprint-6.md
  docs/docs/sprints/sprint-7.md
Labels: documentation

#65 feature#61/update-search-page
  src/app/search/page.tsx
Labels: feature

#66 Feature#63/update contribute
  docs/docs/contributing.md
  docs/docs/environment.md
  docs/docs/sprints/sprint-7.md
  docs/docs/sprints/sprint-8.md
  docs/mkdocs.yml
Labels: documentation

#70 Feature #67/search structure
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/Filter.tsx
  src/components/FilterSearch.tsx
  src/data/filtersData.ts
Labels: feature, design, enhancement

#71 Feature #68/initial service
  src/app/search/page.tsx
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
Labels: feature

#77 Feature #73/responsive home
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/Header.tsx
Labels: design

#79 Feature#74/initialize tests
  package-lock.json
  package.json
  src/hooks/useIsMobile.tsx
  vitest.config.ts
Labels: testing, enhancement

#81 tests#80: includes header unit tests
  src/components/Header.spec.tsx
Labels: testing

#90 ci#82: includes quality pipeline
  .github/workflows/quality.yaml
  src/app/search/page.tsx
  src/components/FilterSearch.tsx
  src/components/Subtopics.tsx
  src/components/Topics.tsx
  vitest-setup.js
Labels: testing, enhancement

#91 Fix#78/responsive rank
  src/app/search/page.tsx
  src/components/FilterSearch.tsx
  src/components/Header.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.tsx
  src/components/Topics.tsx
  src/components/chart/GroupedBar.tsx
  src/components/chart/StackedColumn.tsx
  src/data/filtersData.ts
  src/services/IndicatorsService.ts
Labels: bug, design

#92 Feature #88/search tests
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/FilterSearch.tsx
  src/components/Ranking.tsx
  vitest.config.ts
Labels: testing

#93 test(#85): implements filter tests
  src/components/FilterSearch.spec.tsx
Labels: testing

#95 test(#83): implements ranking tests
  src/components/Ranking.spec.tsx
Labels: testing

#96 Feature #89/home test
  src/app/page.spec.tsx
  src/components/Subtopics.spec.tsx
  src/components/Subtopics.tsx
  src/components/Topics.spec.tsx
  src/components/Topics.tsx
Labels: testing

#97 Feature #86/grouped bar chart tests
  src/components/chart/GroupedBar.spec.tsx
  src/components/chart/GroupedBar.tsx
Labels: testing

#98 test(#87): implements stacked chart tests
  src/components/chart/StackedColumn.spec.tsx
  src/components/chart/StackedColumn.tsx
Labels: testing
