Repository unb-mds/2024-1-EducaMinas-frontend, pull requests merged in 2024-04, with the labels that each got.

#18 Feature #11/deploy mkdocs
  .github/templates/workflows/workflow.yaml
Labels: feature, testing

#29 Fix(#11) deploy MkDocs in Github Pages
  .github/templates/workflows/workflow.yaml
  .github/workflows/workflow.yaml
  docs/docs/about.md
  docs/mkdocs.yml
Labels: bug, feature, documentation, testing

#37 Feature #30/create home page
  package-lock.json
  package.json
  public/home.png
  public/logo.png
  src/app/about/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/hooks/useIsMobile.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feature, design

#52 Feature #49/implements filtes
  package-lock.json
  package.json
  src/app/search/page.tsx
  src/components/Filter.tsx
Labels: feature, design
