Repository unb-mds/2024-1-EducaMinas-frontend, pull requests merged in 2024-08, with the labels that each got.

#102 Feature#99/documentation
  .github/workflows/workflow.yaml
  docs/docs/sprints/sprint-10.md
  docs/docs/sprints/sprint-11.md
  docs/docs/sprints/sprint-9.md
  docs/mkdocs.yml
Labels: documentation

#103 Feature #100/select options value
  src/app/search/page.tsx
  src/components/FilterSearch.spec.tsx
  src/components/FilterSearch.tsx
  src/data/filtersData.ts
Labels: performance, testing, enhancement

#107 Feature#104/backend connection
  .env
  .gitignore
  src/app/search/page.tsx
  src/lib/axios.ts
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
  src/types/Enrollment.ts
  src/types/Indicator.ts
  src/types/Ranking.ts
Labels: feature, performance, enhancement

#108 Feature#106/next deploy
  .github/workflows/deploy-docs.yaml
  .github/workflows/deploy-next.yaml
  .github/workflows/quality.yaml
Labels: performance, enhancement

#109 updates main
  .env
  .github/workflows/deploy-docs.yaml
  .github/workflows/deploy-next.yaml
  .github/workflows/quality.yaml
  .gitignore
  docs/docs/contributing.md
  docs/docs/environment.md
  docs/docs/project/servicos.md
  docs/docs/sprints/sprint-10.md
  docs/docs/sprints/sprint-11.md
  docs/docs/sprints/sprint-6.md
  docs/docs/sprints/sprint-7.md
  docs/docs/sprints/sprint-8.md
  docs/docs/sprints/sprint-9.md
  docs/mkdocs.yml
  package-lock.json
  package.json
  src/app/page.spec.tsx
  src/app/page.tsx
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/Filter.tsx
  src/components/FilterSearch.spec.tsx
  src/components/FilterSearch.tsx
  src/components/Header.spec.tsx
  src/components/Header.tsx
  src/components/Ranking.spec.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.spec.tsx
  src/components/Subtopics.tsx
  src/components/Topics.spec.tsx
  src/components/Topics.tsx
  src/components/chart/GroupedBar.spec.tsx
  src/components/chart/GroupedBar.tsx
  src/components/chart/StackedColumn.spec.tsx
  src/components/chart/StackedColumn.tsx
  src/data/filtersData.ts
  src/hooks/useIsMobile.tsx
  src/lib/axios.ts
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
  src/types/Enrollment.ts
  src/types/Indicator.ts
  src/types/Ranking.ts
  vitest-setup.js
  vitest.config.ts
Labels: bug, feature, documentation, performance, testing, enhancement

#110 chore#106: update jobs names
  .github/workflows/deploy-docs.yaml
  .github/workflows/deploy-next.yaml
  .github/workflows/quality.yaml
Labels: design

#113 tests: includes pre commit testing lib
  package-lock.json
  package.json
Labels: testing, enhancement

#111 Feature #101/graphic informations
  src/app/search/page.tsx
  src/components/Popup.spec.tsx
  src/components/Popup.tsx
  src/components/Subtopics.spec.tsx
  src/components/Subtopics.tsx
Labels: feature, testing

#114 Feature #105/clean code
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/FilterSearch.spec.tsx
  src/components/FilterSearch.tsx
  src/components/Header.spec.tsx
  src/components/Header.tsx
  src/components/Popup.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.tsx
  src/components/chart/GroupedBar.spec.tsx
  src/data/filtersData.ts
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
Labels: design, testing, enhancement

#117 Fix #114/charts data
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/data/filtersData.ts
Labels: bug, enhancement

#121 Feature#118/usable ranking
  package.json
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/FilterSearch.tsx
  src/components/Ranking.spec.tsx
  src/components/Ranking.tsx
  src/data/filtersData.ts
Labels: feature, design, testing, enhancement

#122 Fix #119/responsive filters
  .github/workflows/deploy-next.yaml
  src/app/search/page.tsx
  src/components/FilterSearch.tsx
Labels: design, enhancement

#123 feat: create preview deployment
  .github/workflows/preview.yaml
Labels: performance, enhancement

#132 fix(#127): fixing filter wrap bug
  src/app/search/page.tsx
Labels: bug

#133 Feature#128/toast sonner
  .env
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/search/page.tsx
  src/lib/axios.ts
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
Labels: feature, design

#134 handle order locale
  .env
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/search/page.tsx
  src/lib/axios.ts
  src/services/EnrollmentService.ts
  src/services/IndicatorsService.ts
  src/services/RankingService.ts
Labels: feature, enhancement

#135 feat(#129): includes codecov in quality cli
  .github/workflows/quality.yaml
  README.md
  package-lock.json
  package.json
Labels: documentation, testing

#139 feat(#129): includes codecov and push on main
  .github/workflows/quality.yaml
Labels: documentation, testing

#141 Feature #126/text informations
  src/app/home/page.spec.tsx
  src/app/home/page.tsx
  src/app/icon.png
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/Popup.spec.tsx
  src/components/Popup.tsx
  src/components/Ranking.tsx
  src/components/Subtopics.spec.tsx
  src/components/Subtopics.tsx
Labels: bug, testing, enhancement

#142 Feature#131/finally documentation
  README.md
  docs/docs/about.md
  docs/docs/assets/arq.png
  docs/docs/contributing-backend.md
  docs/docs/contributing-frontend.md
  docs/docs/contributing.md
  docs/docs/environment.md
  docs/docs/index.md
  docs/docs/project/arquitetura.md
  docs/docs/project/eap.md
  docs/docs/project/requirements.md
  docs/docs/project/servicos.md
  docs/docs/project/storymap.md
  docs/docs/sprints/sprint-0.md
  docs/docs/sprints/sprint-1.md
  docs/docs/sprints/sprint-10.md
  docs/docs/sprints/sprint-11.md
  docs/docs/sprints/sprint-12.md
  docs/docs/sprints/sprint-13.md
  docs/docs/sprints/sprint-14.md
  docs/docs/sprints/sprint-2.md
  docs/docs/sprints/sprint-3.md
  docs/docs/sprints/sprint-4.md
  docs/docs/sprints/sprint-5.md
  docs/docs/sprints/sprint-6.md
  docs/docs/sprints/sprint-7.md
  docs/docs/sprints/sprint-8.md
  docs/docs/sprints/sprint-9.md
  docs/docs/template/issuetemplate.md
  docs/docs/template/prTemplate.md
  docs/mkdocs.yml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/FilterSearch.spec.tsx
  src/components/Header.spec.tsx
  src/components/Header.tsx
  src/components/Ranking.spec.tsx
  src/components/Ranking.tsx
  vitest-setup.js
  vitest.config.ts
Labels: feature, documentation, testing, enhancement

#143 feat(#115): includes about page and tests
  next.config.mjs
  src/app/about/page.spec.tsx
  src/app/about/page.tsx
Labels: feature, testing

#145 Feature #144/align frontend
  src/app/search/page.spec.tsx
  src/app/search/page.tsx
  src/components/Ranking.tsx
  src/data/filtersData.ts
  src/services/IndicatorsService.ts
Labels: performance, testing, enhancement

#146 Feature#130/backend mkdocs
  README.md
  docs/docs/contributing-backend.md
  docs/docs/project/arquitetura.md
  src/app/search/page.tsx
  src/components/chart/GroupedBar.tsx
Labels: bug, documentation, design

#148 chore(#147): includes about texts and links and fixing ranking bug
  package-lock.json
  package.json
  src/app/about/page.tsx
  src/app/search/page.tsx
Labels: feature
