Repository unb-mds/2024-1-EducaMinas-frontend, pull requests merged in 2024-09, with the labels that each got.

#152 Feature #151/graphics order
  docs/docs/assets/arq.png
  src/app/about/page.tsx
  src/app/home/page.spec.tsx
  src/app/home/page.tsx
  src/app/search/page.tsx
  src/components/Popup.tsx
  src/components/Subtopics.tsx
  src/components/Topics.spec.tsx
  src/components/Topics.tsx
  src/data/filtersData.ts
Labels: design, enhancement

#153 Fix/align texts
  src/app/about/page.tsx
  src/components/Popup.tsx
Labels: design

#154 Feature#150/increase documentation
  docs/docs/index.md
  docs/docs/project/arquitetura.md
  docs/docs/project/personas.md
  src/app/search/page.tsx
Labels: documentation
